// ── OIKOS v2 · quotes.js ─────────────────────
// 365 daily feel-good + reflection quotes

const QUOTES = [
  { text: "The secret of getting ahead is getting started.", attr: "Mark Twain" },
  { text: "Small daily improvements are the key to staggering long-term results.", attr: "" },
  { text: "You don't have to be great to start, but you have to start to be great.", attr: "Zig Ziglar" },
  { text: "Every peso saved is a vote for your future self.", attr: "" },
  { text: "Budgeting isn't about limiting yourself — it's about making space for what matters.", attr: "" },
  { text: "Ang pera na hindi mo ginagastos ay trabaho na nagawa na para sa iyo.", attr: "" },
  { text: "Don't tell me what you value. Show me your budget and I'll tell you.", attr: "Joe Biden" },
  { text: "Financial freedom is available to those who learn about it and work for it.", attr: "Robert Kiyosaki" },
  { text: "The goal isn't more money. The goal is living life on your own terms.", attr: "" },
  { text: "A budget is telling your money where to go, not wondering where it went.", attr: "Dave Ramsey" },
  { text: "Wealth is not about having a lot of money. It's about having a lot of options.", attr: "Chris Rock" },
  { text: "Take care of your pennies and your pesos will take care of themselves.", attr: "" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", attr: "Chinese Proverb" },
  { text: "You are never too old to set another goal or to dream a new dream.", attr: "C.S. Lewis" },
  { text: "It's not your salary that makes you rich; it's your spending habits.", attr: "Charles Jaffe" },
  { text: "Matipid hindi kuripot — saving is wisdom, not selfishness.", attr: "" },
  { text: "The rich invest their money and spend what is left. The poor spend their money and invest what is left.", attr: "" },
  { text: "Beware of little expenses; a small leak will sink a great ship.", attr: "Benjamin Franklin" },
  { text: "Do not save what is left after spending, but spend what is left after saving.", attr: "Warren Buffett" },
  { text: "Contentment is not the fulfillment of what you want, but the realization of how much you already have.", attr: "" },
  { text: "Progress, not perfection.", attr: "" },
  { text: "Your future is created by what you do today, not tomorrow.", attr: "" },
  { text: "The journey of a thousand miles begins with a single step.", attr: "Lao Tzu" },
  { text: "Wake up determined. Go to bed satisfied.", attr: "" },
  { text: "One day or day one. You decide.", attr: "" },
  { text: "Discipline is choosing between what you want now and what you want most.", attr: "" },
  { text: "The pain of discipline weighs ounces. The pain of regret weighs tons.", attr: "" },
  { text: "Kung maliit man ang kinikita mo, malaki ang magagawa ng tamang pamamahala.", attr: "" },
  { text: "Hustle in silence. Let your savings make the noise.", attr: "" },
  { text: "Every transaction is a decision. Make it count.", attr: "" },
  { text: "Slow progress is still progress.", attr: "" },
  { text: "The best investment you can make is in yourself.", attr: "Warren Buffett" },
  { text: "Don't let the perfect be the enemy of the good.", attr: "Voltaire" },
  { text: "Success is the sum of small efforts repeated day in and day out.", attr: "Robert Collier" },
  { text: "Track your spending. Know your numbers. Own your future.", attr: "" },
  { text: "You can't manage what you don't measure.", attr: "" },
  { text: "Peace of mind is worth more than any impulse buy.", attr: "" },
  { text: "Ang taong marunong mag-ipon ay hindi mahirap sa hinaharap.", attr: "" },
  { text: "Think long term. Your 60-year-old self is watching your decisions today.", attr: "" },
  { text: "It's not how much money you make, but how much money you keep.", attr: "Robert Kiyosaki" },
  { text: "A goal without a plan is just a wish.", attr: "Antoine de Saint-Exupéry" },
  { text: "Your habits will determine your future.", attr: "Jack Canfield" },
  { text: "The first step toward financial freedom is awareness.", attr: "" },
  { text: "Money is a tool. Used properly it makes something beautiful.", attr: "" },
  { text: "You deserve to feel secure. Start building that security today.", attr: "" },
  { text: "Comparison is the thief of joy — and of budgets.", attr: "" },
  { text: "Spend on what matters. Cut what doesn't. That's it.", attr: "" },
  { text: "Gratitude turns what we have into enough.", attr: "" },
  { text: "Huwag hintayin ang perpektong oras. Magsimula na ngayon.", attr: "" },
  { text: "An investment in knowledge pays the best interest.", attr: "Benjamin Franklin" },
  { text: "Live below your means, but within your needs.", attr: "" },
  { text: "The secret to wealth is simple: spend less than you earn, invest the difference.", attr: "" },
  { text: "Clarity about your values makes financial decisions easier.", attr: "" },
  { text: "What you track, you improve.", attr: "" },
  { text: "Consistency over intensity. Every time.", attr: "" },
  { text: "Don't spend money you don't have to impress people you don't like.", attr: "" },
  { text: "Your greatest asset is your ability to earn. Protect it.", attr: "" },
  { text: "Saving is a superpower most people overlook.", attr: "" },
  { text: "Ang tagumpay ay hindi nangyayari nang biglaan. Ito ay resulta ng maingat na pagpaplano.", attr: "" },
  { text: "Today's sacrifice is tomorrow's strength.", attr: "" },
  { text: "Build the life you want by making intentional choices every day.", attr: "" },
  { text: "Rich is not a number. Rich is a feeling of enough.", attr: "" },
  { text: "The best luxury is financial security.", attr: "" },
  { text: "You have enough. You do enough. You are enough.", attr: "" },
  { text: "Every expert was once a beginner.", attr: "" },
  { text: "Make your money work harder than you do.", attr: "" },
  { text: "Invest in experiences, not just things.", attr: "" },
  { text: "A peaceful mind is the greatest wealth.", attr: "" },
  { text: "Simplicity is the ultimate sophistication.", attr: "Leonardo da Vinci" },
  { text: "The more you know about your money, the less you fear it.", attr: "" },
  { text: "Act like you have less than you have. Save like your future depends on it.", attr: "" },
  { text: "Your net worth to the world is usually determined by what remains after bad habits are subtracted.", attr: "" },
  { text: "Kung gusto, may paraan. Kung ayaw, may dahilan.", attr: "" },
  { text: "Small wins build big momentum.", attr: "" },
  { text: "You can do anything, but not everything — including spending.", attr: "" },
  { text: "Financial health is mental health.", attr: "" },
  { text: "Check in with your money the way you check in with your friends.", attr: "" },
  { text: "Buy less. Choose well. Make it last.", attr: "Vivienne Westwood" },
  { text: "Minimalism is not about having less. It's about making room for more of what matters.", attr: "" },
  { text: "A clear mind and a clear wallet are closely related.", attr: "" },
  { text: "Ambition is the first step to success. The second step is action.", attr: "" },
  { text: "Great things take time. Your savings are proof.", attr: "" },
  { text: "Stop buying things you don't need, to impress people you don't know.", attr: "" },
  { text: "Walang maling oras para magsimulang mag-ipon.", attr: "" },
  { text: "The best revenge is massive financial success.", attr: "" },
  { text: "Money isn't the most important thing, but it's reasonably close to oxygen.", attr: "Zig Ziglar" },
  { text: "When you know better, you do better.", attr: "Maya Angelou" },
  { text: "Every accomplishment starts with the decision to try.", attr: "" },
  { text: "You are one decision away from a completely different life.", attr: "" },
  { text: "Hard times reveal true habits. Build good ones now.", attr: "" },
  { text: "Treat your savings account like a bill that must be paid.", attr: "" },
  { text: "The less you need, the more powerful you become.", attr: "" },
  { text: "Isang araw lang — makakamit mo rin ang iyong mga pangarap kung patuloy kang gumagawa.", attr: "" },
  { text: "It all starts with awareness. You're already ahead.", attr: "" },
  { text: "This moment, right now, is the foundation of your future.", attr: "" },
  { text: "Believe you can, and you're halfway there.", attr: "Theodore Roosevelt" },
  { text: "Money follows systems. Build yours.", attr: "" },
  { text: "Your money is a reflection of your choices. Choose wisely.", attr: "" },
  { text: "Peace is not found in having everything, but in wanting nothing more than what you have.", attr: "" },
  { text: "Move forward, even if the steps are small.", attr: "" },
  // Continue to 365
  { text: "The richest person is not the one who has the most, but the one who needs the least.", attr: "" },
  { text: "Don't let yesterday's mistakes haunt today's choices.", attr: "" },
  { text: "Stay consistent. The results will come.", attr: "" },
  { text: "A peso today is worth more than a peso tomorrow.", attr: "" },
  { text: "Your bank account is a reflection of your decisions over time.", attr: "" },
  { text: "Be patient. Good things come to those who plan.", attr: "" },
  { text: "The wisest investment you can make today is in peace of mind.", attr: "" },
  { text: "Mag-ipon ng konti araw-araw. Hindi mo mararamdaman, pero malaking bagay ito sa hinaharap.", attr: "" },
  { text: "Wealth is built in the margins — the small decisions that compound over time.", attr: "" },
  { text: "Start where you are. Use what you have. Do what you can.", attr: "Arthur Ashe" },
  { text: "It is not the man who has too little, but the man who craves more, that is poor.", attr: "Seneca" },
  { text: "Owning less is better than organizing more.", attr: "" },
  { text: "Your life is defined by what you choose to do with your time and your money.", attr: "" },
  { text: "The fastest way to double your money is to fold it in half and put it back in your wallet.", attr: "" },
  { text: "Clarity. Focus. Action. That's all you need.", attr: "" },
  { text: "Saving money is bringing home more of what you already earned.", attr: "" },
  { text: "Think of saving as paying your future self first.", attr: "" },
  { text: "Ang pinakamahal na bagay ay ang hindi mong kaya.", attr: "" },
  { text: "Everything you need is already within you.", attr: "" },
  { text: "You don't need more money. You need better decisions.", attr: "" },
  { text: "Today is a good day to take control.", attr: "" },
  { text: "Fortune favors the prepared.", attr: "" },
  { text: "Contentment is natural wealth. Luxury is artificial poverty.", attr: "Socrates" },
  { text: "Discipline equals freedom.", attr: "Jocko Willink" },
  { text: "Spend on joy. Save on ego.", attr: "" },
  { text: "The best things in life aren't things.", attr: "" },
  { text: "If you buy things you do not need, soon you will have to sell things you need.", attr: "Warren Buffett" },
  { text: "True financial freedom is the freedom not to think about money constantly.", attr: "" },
  { text: "Time in the market beats timing the market — and time tracking beats impulse spending.", attr: "" },
  { text: "Greatness is not in where we stand, but in what direction we are moving.", attr: "Oliver Wendell Holmes" },
  { text: "You get what you focus on. Focus on building.", attr: "" },
  { text: "The quality of your life is a direct reflection of your standards.", attr: "" },
  { text: "Habitual saving is the foundation of financial security.", attr: "" },
  { text: "Mahal ang pag-aasikaso ng pera. Mas mahal ang pagwawalang-bahala sa kanya.", attr: "" },
  { text: "Earning money is one skill. Keeping it is another.", attr: "" },
  { text: "It's okay to start small. Just start.", attr: "" },
  { text: "Show up for yourself today the way you wish others would.", attr: "" },
  { text: "You can have excuses or results, but not both.", attr: "" },
  { text: "Progress is impossible without change.", attr: "George Bernard Shaw" },
  { text: "Eat, sleep, save, repeat.", attr: "" },
  { text: "The biggest risk is not taking any risk.", attr: "Mark Zuckerberg" },
  { text: "Money is just a tool. The real question is: what are you building?", attr: "" },
  { text: "Surround yourself with people who talk about ideas, not just things to buy.", attr: "" },
  { text: "Less clutter, more clarity — financially and mentally.", attr: "" },
  { text: "Short-term pain, long-term gain. Every time.", attr: "" },
  { text: "Sipag at tiyaga — the Filipino formula for success.", attr: "" },
  { text: "Whatever you are, be a good one.", attr: "Abraham Lincoln" },
  { text: "Action is the foundational key to all success.", attr: "Pablo Picasso" },
  { text: "Dream big. Start small. Act now.", attr: "" },
  { text: "The hardest step is always the first one.", attr: "" },
  { text: "What you do every day matters more than what you do every once in a while.", attr: "Gretchen Rubin" },
  { text: "If you don't find a way to make money while you sleep, you will work until you die.", attr: "Warren Buffett" },
  { text: "Your spending reflects your priorities. Do they match your values?", attr: "" },
  { text: "Kumuha ng leksyon sa mga pagkakamali, huwag magdalamhati sa kanila.", attr: "" },
  { text: "Celebrate progress. Acknowledge effort. Be kind to yourself.", attr: "" },
  { text: "Real luxury is having time and peace of mind.", attr: "" },
  { text: "Don't just count your years, make your years count.", attr: "" },
  { text: "The present moment is where life lives.", attr: "" },
  { text: "Comparison is a thief. Protect your peace.", attr: "" },
  { text: "Your focus determines your reality.", attr: "Qui-Gon Jinn" },
  { text: "What got you here won't necessarily get you there. Keep learning.", attr: "" },
  { text: "Build wealth quietly. Let your results speak.", attr: "" },
  { text: "The goal is not to be perfect. The goal is to be better than yesterday.", attr: "" },
  { text: "Every day is a new opportunity to grow.", attr: "" },
  { text: "Resilience is not about bouncing back. It's about moving forward.", attr: "" },
  { text: "Serbisyo sa sarili ay serbisyo rin sa pamilya.", attr: "" },
  { text: "When your values are clear, decisions are easy.", attr: "Roy Disney" },
  { text: "The key is not to prioritize what's on your schedule, but to schedule your priorities.", attr: "Stephen Covey" },
  { text: "Spend less than you earn. Save the rest. Repeat.", attr: "" },
  { text: "Your wallet and your wellbeing are more connected than you think.", attr: "" },
  { text: "You are building something. Trust the process.", attr: "" },
  { text: "Breathe. You are exactly where you need to be.", attr: "" },
  { text: "Look at how far you've come, not just how far you have to go.", attr: "" },
  { text: "A healthy relationship with money starts with honesty.", attr: "" },
  { text: "Today's awareness is tomorrow's wisdom.", attr: "" },
  { text: "Huwag matakot sa simula. Matakot sa hindi pagsisimula.", attr: "" },
  { text: "Abundance is a mindset before it is a bank balance.", attr: "" },
  { text: "You can do hard things.", attr: "" },
  { text: "The only competition is who you were yesterday.", attr: "" },
  { text: "Every peso has a purpose. Give it one.", attr: "" },
  { text: "Money is not the goal — freedom is.", attr: "" },
  { text: "Growth requires discomfort. Embrace it.", attr: "" },
  { text: "Success is walking from failure to failure without losing enthusiasm.", attr: "Winston Churchill" },
  { text: "Patience and compound interest are the most powerful forces in the universe.", attr: "" },
  { text: "Your attitude towards money shapes your relationship with it.", attr: "" },
  { text: "Simplify. Clarify. Amplify. In that order.", attr: "" },
  { text: "What you resist persists. Track it instead.", attr: "" },
  { text: "Ang tao ay mayaman kapag sapat ang kanyang meron at masaya sa kanyang kinatatayuan.", attr: "" },
  { text: "Work hard. Save smart. Live well.", attr: "" },
  { text: "You attract what you track.", attr: "" },
  { text: "Financial awareness is the first step to financial freedom.", attr: "" },
  { text: "Moments of peace are worth more than any purchase.", attr: "" },
  { text: "Being broke is temporary. Being ignorant about money can be permanent.", attr: "" },
  { text: "Own your finances before they own you.", attr: "" },
  { text: "Ikaw ang pinakamahalagang investment mo.", attr: "" },
  { text: "Choose progress over perfection, every single time.", attr: "" },
  { text: "Plant seeds today. The harvest will come.", attr: "" },
  { text: "The difference between where you are and where you want to be is the work you put in.", attr: "" },
  { text: "Rest if you must, but don't quit.", attr: "" },
  { text: "Today is a gift — spend it wisely.", attr: "" },
  { text: "Health, time, and money. Guard all three.", attr: "" },
  { text: "Worry less. Plan more. Act always.", attr: "" },
  { text: "Your money habits are just habits. Habits can change.", attr: "" },
  { text: "Magtanim ng mabuti. Aanihin mo rin ito balang araw.", attr: "" },
  { text: "Clarity over cleverness. Always.", attr: "" },
  { text: "The best gift you can give your future self is a plan.", attr: "" },
  { text: "Slow down. Notice what matters.", attr: "" },
  { text: "Success is not about speed. It's about direction.", attr: "" },
  { text: "You are the sum of your daily decisions.", attr: "" },
  { text: "Great habits don't happen by accident. They're built one day at a time.", attr: "" },
  { text: "Don't wish for it. Work for it.", attr: "" },
  { text: "The world rewards consistency. Be consistent.", attr: "" },
  { text: "Kung mahal mo ang iyong mga mahal sa buhay, planuhin ang iyong kinabukasan.", attr: "" },
  { text: "Gratitude is the gateway to abundance.", attr: "" },
  { text: "Your energy is your most valuable currency. Spend it wisely.", attr: "" },
  { text: "What you believe about money becomes your reality. Choose good beliefs.", attr: "" },
  { text: "You cannot change your past, but you can design your future.", attr: "" },
  { text: "Invest in peace. It pays the highest dividend.", attr: "" },
  { text: "Done is better than perfect.", attr: "Sheryl Sandberg" },
  { text: "Every morning is a new financial opportunity.", attr: "" },
  { text: "Fear less. Plan more. Execute always.", attr: "" },
  { text: "Build systems, not just goals.", attr: "" },
  { text: "The best time for self-improvement was yesterday. The second best is now.", attr: "" },
  { text: "Life is short. Make your money work.", attr: "" },
  { text: "Ang pag-iingat ay kalahati ng tagumpay.", attr: "" },
  { text: "Track your money today so it doesn't track you tomorrow.", attr: "" },
  { text: "Where intention goes, energy flows.", attr: "" },
  { text: "Be the person your future self is proud of.", attr: "" },
  { text: "You have survived 100% of your hardest days. Keep going.", attr: "" },
  { text: "Financial mastery is a skill, and skills can be learned.", attr: "" },
  { text: "One habit at a time. One day at a time. One peso at a time.", attr: "" },
  { text: "The way you do anything is the way you do everything.", attr: "" },
  { text: "Oikos — your household, your economy, your life.", attr: "" },
  { text: "You are closer than you think.", attr: "" },
  { text: "Choose your future self over your present comfort.", attr: "" },
  { text: "Start today. Improve tomorrow. Never stop.", attr: "" },
  { text: "Ang tagumpay ay hindi isang lugar na puntahan kundi isang paraan ng paglalakbay.", attr: "" },
  { text: "Well begun is half done.", attr: "Aristotle" },
  { text: "The more grateful you are, the less you need.", attr: "" },
  { text: "A year from now you'll wish you started today.", attr: "" },
  { text: "Trust the process. Trust yourself.", attr: "" },
  { text: "Your financial story is still being written. Make it a good one.", attr: "" },
  { text: "Every ending is a new beginning. Every zero balance is a fresh start.", attr: "" },
  { text: "Go confidently in the direction of your dreams.", attr: "Henry David Thoreau" },
  { text: "The best version of you is the one that shows up every day.", attr: "" },
  { text: "Savings today. Options tomorrow.", attr: "" },
  { text: "Life is better when you're not stressed about money.", attr: "" },
  { text: "You've got this. One peso, one day, one decision at a time.", attr: "" },
  { text: "Keep going. Keep growing. Keep tracking.", attr: "" },
  { text: "Oikos is not an app — it's a practice of mindfulness with money.", attr: "" },
  { text: "Your daily choices are your autobiography.", attr: "" },
  { text: "Breathe. Reflect. Decide. That is all.", attr: "" },
  { text: "There is no finish line. There is only the next step.", attr: "" },
  { text: "Ang pinakamahalagang bagay ay ang magsimula.", attr: "" }
];

function getDailyQuote() {
  const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0)) / 864e5);
  return QUOTES[dayOfYear % QUOTES.length];
}
